language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
